### PR TITLE
fix use of point processes with iterable parameters

### PR DESCRIPTION
**Pull request by espenhgn**
Hi @Helveg, 
If you agree, please merge this into your working branch and I'll merge the corresponding PR into LFPy@2.2.dev0. All tests should pass.

### CODE REVIEW

**Comment by Helveg** [comment]
How about:

```python
                    for key, value in kwargs.items():
                        try:
                          itr = iter(value)
                        except TypeError:
                            setattr(stim, key, value)
                        else:
                            for i, v in itr:
                                getattr(stim, key)[i] = v
```

This avoids a type check and delegation to numpy, `iter` is Python's single source of truth to determine "is this iterable?".

**Comment by espenhgn** [comment]
It doesn't work with the unit tests, unfortunately:
```
        for sec in self.allseclist:
            for seg in sec:
                if i == idx:
                    command = cmd1 + pptype + cmd2
                    stim = eval(command, locals(), globals())
                    for key, value in kwargs.items():
                        try:
                          itr = iter(value)
                        except TypeError:
                            setattr(stim, key, value)
                        else:
>                           for i, v in itr:
E                           TypeError: cannot unpack non-iterable int object
```

**Comment by Helveg** [comment]
Oh, ofcourse, I forgot `enumerate(itr)`!

**Comment by Helveg** [comment]
Tests passed ! I went ahead and merged.

**Comment by espenhgn** [comment]
Great!

**Pull request merged**
